name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "first job executed"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "second job executed"
  third-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "parallel with first-job"
